name = "w-campus"
account_id = "85c8e953bdefb825af5374f0d66ca5dc"
compatibility_date = "2025-09-11"
pages_build_output_dir = "./dist"

[vars]
SITE_NAME = "WOW-CAMPUS"
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "w-campus-production-fresh"
database_id = "d5248baa-5bf3-4292-bfc1-a81c2c44c7a4"

[env.preview]
name = "w-campus-preview"
[env.preview.vars]
ENVIRONMENT = "preview"
SITE_NAME = "WOW-CAMPUS"

# Use a separate D1 database for preview/dev
[[env.preview.d1_databases]]
binding = "DB"
database_name = "w-campus-preview-fresh"
database_id = "934a21ca-0900-4b2e-a52f-9a43e24a0fa2"
preview_database_id = "934a21ca-0900-4b2e-a52f-9a43e24a0fa2"