name = "w-campus"
main = "dist/index.js"
compatibility_date = "2025-09-11"

[vars]
SITE_NAME = "WOW-CAMPUS"
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "w-campus-production-fresh"
database_id = "d5248baa-5bf3-4292-bfc1-a81c2c44c7a4"