env:
  NODE_VERSION: '20'

jobs:
  build-and-deploy:
    steps:
    - name: Build project
      run: node --require ./setup-polyfills.cjs ./node_modules/.bin/vite build
      env:
        NODE_ENV: production
        
    - name: Deploy to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        projectName: w-campus-com  # 이 부분이 중요!
